src/Entity/Author.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Author
 *
 * @ORM\Table(name="author")
 * @ORM\Entity(repositoryClass="App\Repository\AuthorRepository")
 */
class Author
{
    /**
     * @var int
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     * @ORM\Column(name="surname", type="string", length=255)
     */
    private $surname;

    /**
     * @var string
     * @ORM\Column(name="username", type="string", length=255, unique=true)
     */
    private $username;

    /**
     * @var string
     * @ORM\Column(name="pseudo", type="string", length=255, unique=true)
     */
    private $pseudo;

    /**
     * @var string
     * @ORM\Column(name="email", type="string", length=255)
     */
    private $email;

    /**
     * @var string
     * @ORM\Column(name="short_bio", type="string", length=500)
     */
    private $shortBio;

    /**
     * @var boolean
     * @ORM\Column(name="is_admin", type="boolean")
     */
    private $isAdmin = false;

    /**
     * Get isAdmin
     * @return boolean
     */
    public function isAdmin()
    {
        return $this->isAdmin;
    }

    /**
     * @param bool $isAdmin
     */
    public function setIsAdmin(bool $isAdmin)
    {
        $this->isAdmin = $isAdmin;
    }


    /**
     * Get id
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     * @param string $name
     * @return Author
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * Get name
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set surname
     * @param string $surname
     * @return Author
     */
    public function setSurname($surname)
    {
        $this->surname = $surname;
        return $this;
    }

    /**
     * Get surname
     * @return string
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     * Set username
     * @param string $username
     * @return Author
     */
    public function setUsername($username)
    {
        $this->username = $username;
        return $this;
    }

    /**
     * Get username
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set pseudo
     * @param string $pseudo
     * @return Author
     */
    public function setPseudo($pseudo)
    {
        $this->pseudo = $pseudo;
        return $this;
    }

    /**
     * Get pseudo
     * @return string
     */
    public function getPseudo()
    {
        return $this->pseudo;
    }

    /**
     * Set email
     * @param string $email
     * @return Author
     */
    public function setEmail($email)
    {
        $this->email = $email;
        return $this;
    }

    /**
     * Get email
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set shortBio
     * @param string $shortBio
     * @return Author
     */
    public function setShortBio($shortBio)
    {
        $this->shortBio = $shortBio;
        return $this;
    }

    /**
     * Get shortBio
     * @return string
     */
    public function getShortBio()
    {
        return $this->shortBio;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>{% block title %}Le cercle des poétes retrouvés{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
</head>
<body>
{% include 'nav_bar.html.twig' %}
{% include 'header.html.twig' %}
{% block body %}{% endblock %}
{% include 'footer.html.twig' %}
<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script src="{{ asset('js/main.js') }}"></script>
<script src="{{ asset('js/dynamicView.js') }}"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
</body>
</html>

templates/errorExeption.html.twig
{% extends "base.html.twig" %}
{% block body %}

    <div class="container">
        <div class="blog-header">
            <h1>AAArgggggggggggggggggggg</h1>
        </div>
    </div>
{% endblock %}

templates/footer.html.twig
{% block footer %}
<footer>
    <div class="row justify-content-center align-items-center">
        <div class=" copyright offset-md-1 col-md-3">
            <p> Copyright © 2018 PEYRAT DAMIEN</p>
        </div>
        <div class="offset-md-1 col-md-3">
                <div class ="mention col-4 justify-content-center">
                <p>Mention Légales</p>
            </div>

        </div>
        <div class="coffset-md-1 col-md-3">
            <p>Politique de confidentialité</p>
        </div>
    </div>
</footer>
{% endblock %}

templates/header.html.twig
{% block header %}
    <header>
        <div class="title offset-1 col-8 d-none d-lg-block">
<h1 class="lcdpr"><span class="letter">L</span>e <span class="letter">C</span>ercle <span class="letter">D</span>es <span class="letter">P</span>oètes <span class="letter">R</span>etrouvés</h1>
        </div>
        <div class="citation offset-8 col-4 d-none d-lg-block">
            <blockquote class ="d-sm-block">"La vertu paradoxale de la lecture est de nous abstraire du monde pour lui trouver un sens." <br />
                <em>Daniel Pennac</em></blockquote>
        </div>
    </header>
{% endblock %}

templates/modal.html.twig
{% block modal %}
    <div id="ex{{ blogPost.id }}" class="modal" style="margin-top: 100px;">
        <div class="row">
            <span class="col-4 category">{{ blogPost.category }}</span>
            <p class=" col-8 datePost">{{ blogPost.getUpdatedAt|date('Y-m-d H:i') }} par
                {% if blogPost.author %}
                    <a href="{{ path('author', {'name': blogPost.author.username|url_encode }) }}">
                        {{ blogPost.author.pseudo }}
                    </a>
                {% else %}
                    Auteur inconnu
                {% endif %}
            </p>
        </div>
        <h3 class="bookTitle"> {{ blogPost.title }} <span class="writer">({{ blogPost.writer }})</span></h3>
        {% if app.user %}
            <img src="{{ blogPost.cover }}" alt="couverture" style="width: 120px; max-height:150px; min-height: 150px;">
        {% else %}
            <img src="{{ blogPost.cover }}" alt="couverture" style="width: 80px; max-height:80px;">
        {% endif %}
        <p class="description"><span class="avis">SYNOPSIS : </span>{{blogPost.description}}</p>
        <div><p class="review"><span class="avis">MON AVIS: </span>{{blogPost.review}}</p></div>
        {% if app.user %}
            <a href="{{ path('display_review', {'blogPostId': blogPost.id, 'slug': blogPost.slug}) }}"><button class="btn btn-primary">Voir les commentaires</button></a>
        {% endif %}
        <hr/>
        <a href="#" rel="modal:close">Fermer</a>
    </div>
{% endblock %}

templates/modalComment.html.twig
{% block modalComment %}
<div id="modalComment" class="modal" style="margin-top: 100px;">
    {% if comments %}
    {% for comment in comments %}
    <article class="row" style="padding: unset">
        <div class="comment col-lg-12 col-xs-12" style="border-radius: 5px;background-color:rgb(242, 242, 242);">
            {% if author.username == comment.author.username%}
                <span class="deleteComment justify-content-right"><a href="{{ path('delete_comment', {'blogPostId':blogPost.id, 'commentId': comment.id,'slug':blogPost.slug, 'route':route}) }}"><i class="fas fa-trash-alt"  title="Supprimer commentaire"></i></a></span>
                <span class="editComment justify-content-right" onclick="main.editComment({{ comment.id }})"><i class="fas fa-comments" title="Editer commentaire"></i></span>
            {% else %}
                {% if author.admin%}
                    <span class="deleteComment justify-content-right"><a href="{{ path('delete_comment', {'blogPostId':blogPost.id, 'commentId': comment.id,'slug':blogPost.slug,'route':route}) }}"><i class="fas fa-trash-alt"  title="Supprimer commentaire"></i></a></span>
                {% endif %}
            {% endif %}
            <form class="col-6 form_update_comment{{ comment.id }}" style="padding: unset; display: none" action="{{ path('update_comment', {'blogPostId':blogPost.id, 'commentId': comment.id,'slug':blogPost.slug,'route':route}) }}"  method="POST">
                <textarea rows="3" name="update_comment" id="update_comment{{ comment.id }}" class="form-control" required="" placeholder="Ecrire un commentaire"></textarea>
                <button class="btn btn-info postComment" type="submit" style="margin-bottom: 20px;">Poster <i class="fas fa-comments"></i></button>
            </form>
            <div class ="postBy"> Posté par <a href="{{ path('author', {'name': comment.author.username|url_encode }) }}">{{ comment.author.pseudo }}  </a> le {{ comment.updatedAt|date('Y-m-d-H:i:s') }}
                <div class="displayComment" id="comment{{ comment.id }}">{{ comment.content|raw }}</div>
            </div>
        </div>
    </article>
    <hr>
    {% endfor %}
</div>
    {% endif %}
{% endblock %}

templates/modalMostBlogComment.html.twig
{% block modalMostBlogComment %}
    <div id="exM{{ blogpostMostCommented.id }}" class="modal" style="margin-top: 100px;">
        <div class="row">
            <span class="col-4 category">{{ blogpostMostCommented.category }}</span>
            <p class=" col-8 datePost">{{ blogpostMostCommented.getUpdatedAt|date('Y-m-d H:i') }} par
                {% if blogpostMostCommented.author %}
                    <a href="{{ path('author', {'name': blogpostMostCommented.author.username|url_encode }) }}">
                        {{ blogpostMostCommented.author.pseudo }}
                    </a>
                {% else %}
                    Auteur inconnu
                {% endif %}
            </p>
        </div>
        <h3 class="bookTitle"> {{ blogpostMostCommented.title }} <span class="writer">({{ blogpostMostCommented.writer }})</span></h3>
        {% if app.user %}
            <img src="{{ blogpostMostCommented.cover }}" alt="couverture" style="width: 120px; max-height:150px; min-height: 150px;">
        {% else %}
            <img src="{{ blogpostMostCommented.cover }}" alt="couverture" style="width: 80px; max-height:80px;">
        {% endif %}
        <p class="description"><span class="avis">SYNOPSIS : </span>{{blogpostMostCommented.description}}</p>
        <div><p class="review"><span class="avis">MON AVIS: </span>{{blogpostMostCommented.review}}</p></div>
        {% if app.user %}
            <a href="{{ path('display_review', {'blogPostId': blogpostMostCommented.id, 'slug': blogpostMostCommented.slug}) }}"><button class="btn btn-primary">Voir les commentaires</button></a>
        {% endif %}
        <hr/>
        <a href="#" rel="modal:close">Fermer</a>
    </div>
{% endblock %}

templates/modalNewBlogpostComment.html.twig
{% block modalNewComment %}
    <div id="exN{{ newBlogpostComment.id }}" class="modal" style="margin-top: 100px;">
        <div class="row">
            <span class="col-4 category">{{ newBlogpostComment.category }}</span>
            <p class=" col-8 datePost">{{ newBlogpostComment.getUpdatedAt|date('Y-m-d H:i') }} par
                {% if newBlogpostComment.author %}
                    <a href="{{ path('author', {'name': newBlogpostComment.author.username|url_encode }) }}">
                        {{ newBlogpostComment.author.pseudo }}
                    </a>
                {% else %}
                    Auteur inconnu
                {% endif %}
            </p>
        </div>
        <h3 class="bookTitle"> {{ newBlogpostComment.title }} <span class="writer">({{ newBlogpostComment.writer }})</span></h3>
        {% if app.user %}
            <img src="{{ newBlogpostComment.cover }}" alt="couverture" style="width: 120px; max-height:150px; min-height: 150px;">
        {% else %}
            <img src="{{ newBlogpostComment.cover }}" alt="couverture" style="width: 80px; max-height:80px;">
        {% endif %}
        <p class="description"><span class="avis">SYNOPSIS : </span>{{newBlogpostComment.description}}</p>
        <div><p class="review"><span class="avis">MON AVIS: </span>{{newBlogpostComment.review}}</p></div>
        {% if app.user %}
            <a href="{{ path('display_review', {'blogPostId': newBlogpostComment.id, 'slug': newBlogpostComment.slug}) }}"><button class="btn btn-primary">Voir les commentaires</button></a>
        {% endif %}
        <hr/>
        <a href="#" rel="modal:close">Fermer</a>
    </div>
{% endblock %}

templates/nav_bar.html.twig
{% block navBar %}
<div class="sticky-top" >
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" style="opacity: 0.9;">
    <a class="navbar-brand" href="{{ path("homepage") }}">Accueil</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            {% if app.user %}
                <li class="nav-item">
                    <a class="nav-link active" href="{{ path("admin_index") }}"><i class="fas fa-toolbox"></i> Journal<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ path('display_form_review') }}"><i class="fas fa-newspaper"></i> Critiques</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ logout_url("secured_area") }}"><i class="fas fa-sign-out-alt"></i>Deconnexion</a>
                </li>
            {% else %}
                <li class="nav">
                    <a class="nav-link active"  href="/connect/auth0"><i class="fas fa-sign-in-alt"></i> Se connecter </a>
                </li>
            {% endif %}
        </ul>
        <form class="form-inline" action="{{ path('search_review') }}"  method="POST">
            <input type="text"  name="search" id="search" class="form-control" placeholder="Titre, Auteur, catégorie... " style="margin-right: 10px;">
            <button class="btn btn-outline-info my-2 my-sm-0" type="submit" > <i class="fas fa-search" title="Rechercher"></i></button>
        </form>
    </div>
</nav>
    <div class="index d-none d-lg-block" style="opacity: 0.9;">
    <div class="btn-toolbar d-flex justify-content-around alphabet" role="toolbar">
        <div class="btn-group index" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'a'}) }}">A</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index' , {'letter':'b'}) }}">B</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'c'}) }}">C</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'d'}) }}">D</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'e'}) }}">E</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'f'}) }}">F</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'g'}) }}">G</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'h'}) }}">H</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'i'}) }}">I</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'j'}) }}">J</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'k'}) }}">K</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'l'}) }}">L</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'m'}) }}">M</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'n'}) }}">N</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'o'}) }}">O</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'p'}) }}">P</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'q'}) }}">Q</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'r'}) }}">R</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'s'}) }}">S</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'t'}) }}">T</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'u'}) }}">U</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'v'}) }}">V</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'w'}) }}">W</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'x'}) }}">X</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'y'}) }}">Y</a></div>
        <div class="btn-group" role="group" aria-label="..."><a  href="{{ path('search_index'  ,{'letter':'z'}) }}">Z</a></div>
    </div>
</div>
</div>
{% endblock %}

templates/rss.html.twig
{% block rss %}
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner d-none d-lg-block">
        <div class="carousel-item active">
            <div class="d-block w-100" src="" alt="Second slide"></div>
        </div>
        {% for actu in rss %}
            <div class="carousel-item ">
                <div class="d-block w-100" src="" alt="First slide"><span>{{ actu.date|date('Y-m-d H:i') }} </span><i class="fas fa-rss" style="color: #fd7e14"></i><a href=" {{ actu.link }}" target="_blank"><h5 class="bookTitle"> {{ actu.title }}</h5></a></div>
                <div>{{ actu.description }}</div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}